products = [
    {
        "_id":1,
        "productname":"Camera",
        "category":"electronics",
        "price":5000
    },
    {
        "_id":2,
        "productname":"Laptop",
        "category":"electronics",
        "price":50000
    },
    {
        "_id":2,
        "productname":"Mobile",
        "category":"electronics",
        "price":15000
    }
]